# Generated by Django 2.1.3 on 2020-03-26 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import map


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.TextField(max_length=100)),
                ('lon', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('phoneNumber', models.TextField(max_length=20)),
                ('category', models.CharField(blank=True, choices=[('K', 'Korean'), ('J', 'Japanese'), ('C', 'Chinese'), ('W', 'Western'), ('A', 'Asian'), ('E', 'Southeast_Asia'), ('S', 'South_America'), ('M', 'Mideast'), ('F', 'Cafe'), ('N', 'Night_Life')], max_length=1)),
                ('business_hour', models.TextField(blank=True, max_length=100)),
                ('folder', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='map.Folder')),
            ],
            options={
                'ordering': ['-folder'],
            },
        ),
        migrations.CreateModel(
            name='RestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_save_name', models.ImageField(upload_to=map.file_upload_path_for_db)),
                ('file_origin_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('file_ext', models.CharField(max_length=10)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restimages', to='map.Restaurant')),
            ],
            options={
                'ordering': ['create_date'],
            },
        ),
    ]
